### ISSUE TITLE
Verify that satellite metadata content is correct

### ISSUE THREAD

**Issue by ferrighi** [metno/S-ENDA-csw-catalog-service#23]
Check metadata on satellite data stored on thredds.

For example: https://thredds.met.no/thredds/catalog/remotesensingsatellite/polar-swath/2021/01/29/catalog.html?dataset=remotesensingsatellite/polar-swath/2021/01/29/noaa19-avhrr-20210129153123-20210129154431.nc

I know there are some problems. E.g the variable names in some of the netcdf files are starting with a number, which are not recommended, and this causes problems with opendap streaming.

There is an PR on the project creating these netcdf files: https://github.com/pytroll/satpy/pull/1525
This will solve this problem.

Then we need to check against MMD (and ACDD)

**Comment by ferrighi** [comment]
Check mmd specifications for satellite data in the gitlab catalogue

**Comment by TAlonglong** [comment]
Check tool https://ops-podaac-tools.jpl.nasa.gov/mcc/

**Comment by TAlonglong** [comment]
Checking file https://thredds.met.no/thredds/fileServer/remotesensingsatellite/polar-swath/2021/02/10/noaa19-avhrr-20210210081614-20210210082912.nc

- check for a comma separated value failed because "keywords" might not be comma separatedValue: Earth Science > Atmosphere > Atmospheric radiation
✓ check for existence passed because "keywords" exists
Description: A comma-separated list of key words and/or phrases. Keywords may be common words or phrases, terms from a controlled vocabulary (GCMD is often used), or URIs for terms from a controlled vocabulary (see also "keywords_vocabulary" attribute).
Value: Earth Science > Atmosphere > Atmospheric radiation

**Comment by TAlonglong** [comment]
_NCProperties is created at create time as described here and should not be regarded
https://www.unidata.ucar.edu/software/netcdf/docs/attribute_conventions.html
